---
- hosts: all
  sudo: true
  vars:
    selfsign_folder: /etc/pki/selfsign
    selfsign_next_cert_name: logstash

  roles:
    - role: logstash 
      logstash_selfsign: true
      logstash_cert: "{{selfsign_folder}}/certs/{{selfsign_next_cert_name}}.crt"
      logstash_key: "{{selfsign_folder}}/private/{{selfsign_next_cert_name}}.key"
      logstash_ca: "{{selfsign_folder}}/CA/{{selfsign_next_cert_name}}.pem"
      logstash_fetch_auth: true
      logstash_fetch_auth_to: /tmp/deleteme
      logstash_sll_copy: false
