---
- hosts: all
  sudo: true
  vars:
    logstash_selfsign: true
    selfsign_folder: /etc/pki/selfsign
    selfsign_next_cert_name: logstash
    logstash_ssl_certificate_path: "{{selfsign_folder}}/certs/{{selfsign_next_cert_name}}.crt"
    logstash_ssl_key_path: "{{selfsign_folder}}/private/{{selfsign_next_cert_name}}.key"

  roles:
    - {role: logstash }


