---
- name: Auth - create key root folder
  file:
    path: "{{ logstash_ssl_dir }}"
    state: directory

- name: Auth - copy cert
  copy:
    src={{ logstash_ssl_cert_file }}
    dest={{ logstash_ssl_dir }}/logstash.crt
    mode=0644
  notify: restart logstash

- name: Auth - copy private key
  copy:
    src={{ logstash_ssl_key_file }}
    dest={{ logstash_ssl_dir }}/logstash.key
    mode=0600
    owner=logstash
    group=logstash
  notify: restart logstash



