---

- name: Auth - copy cert
  copy:
    src={{ logstash_local_cert }}
    dest={{ logstash_cert }}
    mode=0644
    owner={{ logstash_user }}
    group={{ logstash_user }}
  notify: restart logstash
  when: logstash_sll_copy_local

- name: Auth - copy private key
  copy:
    src={{ logstash_local_key }}
    dest={{ logstash_key }}
    mode=0600
    owner={{ logstash_user }}
    group={{ logstash_user }}
  notify: restart logstash
  when: logstash_sll_copy_local

- name: ensure rights to private key
  file:
    path={{ logstash_key }}
    state=file
    mode=0600
    owner={{ logstash_user }}
    group={{ logstash_user }}
  notify: restart logstash
  when: logstash_sll_copy_local




