---
- name: config - remove conf.d folder
  file:
    state=absent
    path=/etc/logstash/conf.d

- name: config - Inputs and Outputs
  template:
    src={{ item }}.j2
    dest=/etc/logstash/{{ item }}
    owner={{ logstash_user }}
    group={{ logstash_user }}
    mode=0644
  with_items:
    - 01-local-syslog-input.conf
    - 02-logstash-forwarder-input.conf
    - 10-basic-filters.conf
    - 50-elasticsearch-output.conf
  notify: restart logstash

- name: config - directories
  file:
    state=directory
    path=/etc/logstash/elasticsearch
    owner={{ logstash_user }}
    group={{ logstash_user }}

- name: config - elastic search templates
  copy:
    src=ossec_template.json
    dest=/etc/logstash/elasticsearch/
    owner={{ logstash_user }}
    group={{ logstash_user }}
    mode=0644

