---
- name: Debian - Add package verify key
  apt_key:
    url: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

# logstash version 1.4
- name: Debian - Add Logstash apt package to apt
  apt_repository:
    repo: 'deb http://packages.elasticsearch.org/logstash/1.4/debian stable main'
    state: present

- name: Debian - Install Logstash Package
  apt: update_cache=yes pkg=logstash state=present

- name: Debian - Use adm group to enable rights to /var/log
  user:
    name: logstash
    group: adm
    #groups: adm

