---
- name: CentOS - Add Elasticsearch package key
  rpm_key:
    key: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

- name: CentOS - Add Logstash yum config to yum
  copy:
    src: logstash.repo
    dest: /etc/yum.repos.d/logstash.repo
    mode: 0644

- name: CentOS - Install Logstash
  yum: pkg=logstash state=present update_cache=yes enablerepo=logstash
