---
- name: logstash - install debian
  include: install_debian.yml
  when: ansible_os_family == "Debian"

- name: logstash - install centos
  include: install_centos.yml
  when: ansible_os_family == "RedHat"

- name: logstash - configure
  include: config.yml

- name: logstash - auth
  include: auth.yml

- stat: path=/etc/init.d/logstash
  register: logstash_oldservice

- name: logstash - disable service included with package
  service: name=logstash state=stopped enabled=no
  when: logstash_oldservice.stat.exists
  ignore_errors: yes

- name: logstash - delete service included with package
  file: path=/etc/init.d/logstash state=absent

- name: logstash - service
  include: runit_service.yml
  vars:
    service_name: logstash
    service_user: "{{logstash_user}}"
    service_group: adm
    service_command: /opt/logstash/bin/logstash agent -f /etc/logstash/conf.d
    service_env_vars: 
      LS_HOME: /var/lib/logstash
      LS_HEAP_SIZE: "500m"
      LS_JAVA_OPTS: "-Djava.io.tmpdir=/var/lib/logstash"
      HOME: /var/lib/logstash

